networks:
  inception:
      name: inception

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
